### ISSUE TITLE
Function key interaction degrades mouse usage on Mac OS X

### ISSUE THREAD

**Issue by abiyogi** [keyboardio/Model01-Firmware#38]
Using the function key after a few minutes creates an issue with mouse/trackpad on Mac OS X. Unplugging and plugging back the keyboard fixes this, after another 20-30 minutes, the same happens. To reproduce this issue, simply use Model 01 on a Mac and use the function keys a few times and try right clicking with your mouse/trackpad.

**Comment by algernon** [comment]
What issue are you seeing? The clicks getting stuck, perhaps?

**Comment by abiyogi** [comment]
Yes, the clicks getting stuck. Both my Magic Mouse and trackpad loose right click and also some minor visual bugs, drag and drop etc. gets messed up, it seems like a special mode in Mac is triggred. There seems to be a bug in the function key toggle w.r.t. the keyboard and it is triggering some signals/key-bouncing issue which makes the mouse misbehave. Is there a way for me to provide some logs? Happy to help!

**Comment by algernon** [comment]
No need to, this is a [known issue](https://github.com/keyboardio/Kaleidoscope-MouseKeys/issues/10), and a fix is pending. If you want to give it a go, and are comfortable with git, you can try keyboardio/Kaleidoscope-MouseKeys#12 (and the two other PRs it depends on).

The root cause is that if you release `Fn` sooner than the mouse key, the mouse key will never get released, and will appear stuck. You can fix it by pressing `Fn` and the mousekey again, and releasing the mousekey first.

The referenced PR addresses this, and will allow you to release keys in any order.

**Comment by abiyogi** [comment]
Thanks, I should have looked into the other repository too! I'll close this one.

**Comment by algernon** [comment]
Starting in this repo is good practice. It is sometimes hard to tell which plugin is responsible for a bug, so filing one against `Model01-Firmware` is a safe bet. It is not a big deal if its a duplicate. :)

**Comment by abiyogi** [comment]
Alright, and yes I am familiar with git, I'll test the commits once I get some time.

**Comment by gedankenexperimenter** [comment]
This issue can probably be closed now, can't it?

**Comment by algernon** [comment]
Yep, this seems to be in Arduino-Boards too. Thanks for the reminder!
